# Generated by Django 4.0.3 on 2022-06-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lotto',
            fields=[
                ('drwNo', models.IntegerField(max_length=9999, primary_key=True, serialize=False)),
                ('drwNoDate', models.DateTimeField(blank=True, null=True)),
                ('drwtNo1', models.IntegerField(max_length=45)),
                ('drwtNo2', models.IntegerField(max_length=45)),
                ('drwtNo3', models.IntegerField(max_length=45)),
                ('drwtNo4', models.IntegerField(max_length=45)),
                ('drwtNo5', models.IntegerField(max_length=45)),
                ('drwtNo6', models.IntegerField(max_length=45)),
                ('dnusNo', models.IntegerField(max_length=45)),
                ('firstAccumamnt', models.PositiveBigIntegerField()),
            ],
        ),
    ]
